name: Retry Tests

on:
  pull_request:
    branches: [main]

jobs:
  verify-user-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Get User Permission
        id: checkAccess
        uses: actions-cool/check-user-permission@v2
        with:
          require: write
          username: ${{ github.triggering_actor }}
      - name: Check User Permission
        if: steps.checkAccess.outputs.require-result == 'false'
        run: |
          echo "${{ github.triggering_actor }} does not have permissions on this repo."
          echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
          echo "Job originally triggered by ${{ github.actor }}"
          exit 1

  test-momento-local-1:
    needs: verify-user-permissions
    runs-on: ubuntu-latest
    env:
      MOMENTO_API_KEY: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Start Momento Local 1
        run: |
          docker run -d -p 8080:8080 gomomento/momento-local --return-error unavailable --error-rpcs get

      - name: Set script permissions
        run: chmod +x ./scripts/build-and-test-package-full-network-outage-retry-tests.sh

      - name: Build and test with Momento Local 1
        env:
          TEST_URL: http://localhost:8080
        run: |
          node -v
          ./scripts/build-and-test-package-full-network-outage-retry-tests.sh

      - name: Clean up Docker Container
        run: docker rm -f momento-local-1 || true

#  test-momento-local-2:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#        with:
#          ref: ${{ github.event.pull_request.head.sha }}
#
#      - name: Install Node
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18
#
#      - name: Start Momento Local 2
#        run: |
#          docker run -d \
#            --name momento-local-2 \
#            -p 8081:8080 \
#            gomomento/momento-local \
#            --entrypoint /momento-local \
#            --return-error unavailable --error-rpcs get --error-count 2
#
#      - name: Build and test with Momento Local 2
#        env:
#          TEST_URL: http://localhost:8081
#        run: |
#          node -v
#          ./scripts/build-and-test-package-temporary-network-outage-retry.sh "client-sdk-nodejs"
#
#      - name: Clean up Docker Container
#        run: docker rm -f momento-local-2 || true
